# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/myles/virtual/teamproject/draughtcraft/media/profile_images/default.png', upload_to='profile_images'),
        ),
    ]
