# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.FloatField(blank=True),
        ),
    ]
