# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0002_auto_20190315_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dac.Beer'),
        ),
    ]
