# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0003_auto_20190319_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='latitude',
            new_name='lat',
        ),
    ]
