# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0004_auto_20190319_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.ImageField(default='review_images/default.png', upload_to='review_images'),
        ),
    ]
