# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0005_review_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='image',
        ),
    ]
