# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0006_auto_20190319_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='business_images/default.png', upload_to='business_images'),
        ),
    ]
