# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dac', '0007_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='avatar',
            new_name='image',
        ),
    ]
